

;
; ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ	This file is generated by The Interactive Disassembler (IDA)	    บ
; บ	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    บ
; บ			 Licensed to: Freeware version			    บ
; ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
;
; Input	MD5   :	DA5FA55C13F54B603C95398640163F6D

; File Name   :	C:\Users\Cyber_User\Documents\Magshimim\Computer-Architecture\Week 5\important\1.exe
; Format      :	MS-DOS executable (EXE)
; Base Address:	1000h Range: 10000h-10450h Loaded length: 450h
; Entry	Point :	1000:0



.model large


; Segment type:	Pure code
seg000 segment byte public 'CODE' use16
assume cs:seg000
assume es:nothing, ss:seg000, ds:nothing, fs:nothing, gs:nothing




start proc near
push	cs
pop	ds
assume ds:seg000
mov	dx, 0Eh
mov	ah, 9
int	21h		; DOS -	PRINT STRING
			; DS:DX	-> string terminated by	"$"
mov	ax, 4C01h
int	21h		; DOS -	2+ - QUIT WITH EXIT CODE (EXIT)
start endp		; AL = exit code

aThisProgramCan	db 'This program cannot be run in DOS m'
db 'ode.',0Dh,0Dh,0Ah
db '$',0

aPe db 'PE',0

db 4Ch,	1, 5, 0, 0A5h, 51h, 59h, 67h, 0
db 1Ah,	2 dup(0), 0D8h,	1, 2 dup(0), 0E0h
db 0, 7, 3, 0Bh, 1, 2, 38h, 0, 0Ch, 3 dup(0)
db 16h,	3 dup(0), 2, 2 dup(0), 80h, 12h
db 3 dup(0), 10h, 3 dup(0), 20h, 4 dup(0)
db 40h,	2 dup(0), 10h, 3 dup(0), 2, 2 dup(0)
db 4, 3	dup(0),	1, 3 dup(0), 4,	8 dup(0)
db 60h,	3 dup(0), 4, 2 dup(0), 0E3h, 6Ah
db 2 dup(0), 3,	5 dup(0), 20h, 2 dup(0)
db 10h,	4 dup(0), 10h, 2 dup(0), 10h, 6	dup(0)
db 10h,	0Ch dup(0), 50h, 2 dup(0), 90h,	2
db 72h dup(0), 2Eh, 74h, 65h, 78h, 74h,	3 dup(0)
db 0Ch,	0Bh, 3 dup(0), 10h, 3 dup(0), 0Ch
db 3 dup(0), 4,	0Eh dup(0), 60h, 0, 50h
db 60h,	2Eh, 64h, 61h, 74h, 61h, 3 dup(0)
db 2Ch,	4 dup(0), 20h, 3 dup(0), 2, 3 dup(0)
db 10h,	0Eh dup(0), 40h, 0, 30h, 0C0h, 2Eh
db 72h,	64h, 61h, 74h, 61h, 2 dup(0), 10h
db 3, 3	dup(0),	30h, 3 dup(0), 4, 3 dup(0)
db 12h,	0Eh dup(0), 40h, 0, 30h, 40h, 2Eh
db 62h,	2 dup(73h), 4 dup(0), 0B8h, 4 dup(0)
db 40h,	16h dup(0), 80h, 0, 40h, 0C0h, 2Eh
db 69h,	64h, 61h, 74h, 61h, 2 dup(0), 90h
db 2, 3	dup(0),	50h, 3 dup(0), 4, 3 dup(0)
db 16h,	0Eh dup(0), 40h, 0, 30h, 0C0h, 1C0h dup(0)
push	bp
mov	bp, sp
sub	sp, 18h
mov	[di-8],	bx
mov	ax, [di+8]
xor	bx, bx
mov	[di-4],	si
mov	ax, [bx+si]
xor	si, si
mov	ax, [bx+si]
cmp	ax, 91h	; '‘'
add	al, al
ja	short loc_10421
cmp	ax, 8Dh	; ''
add	al, al
jb	short loc_10440

loc_103E5:
mov	si, 1
db 2 dup(0)

loc_103EA:
mov	word ptr [si], 824h
db 3 dup(0), 31h, 0D2h,	89h, 54h, 24h, 4
db 0E8h, 44h, 0Ah, 2 dup(0), 83h, 0F8h,	1
db 74h,	7Ah, 85h, 0C0h,	74h, 0Eh, 0C7h,	4
db 24h,	8, 3 dup(0), 0FFh, 0D0h, 0BBh, 4 dup(0FFh)

loc_10413:
mov	ax, bx
mov	si, [di-4]
mov	bx, [di-8]
mov	sp, bp
pop	bp
retn	4

loc_10421:
cmp	ax, 94h	; '”'
add	al, al
jz	short loc_103EA
ja short loc_10413
cmp	ax, 93h	; '“'
add	al, al
jz	short loc_103E5
mov	ax, bx
mov	si, [di-4]
mov	bx, [di-8]
mov	sp, bp
pop	bp
retn	4


loc_10440:
cmp	ax, 5
add	al, al
jz	short loc_10413
cmp	ax, 1Dh
add	al, al
jnz	short loc_10413
db 0C7h	; ว
db    4
seg000 ends


end start
