

;
; ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ	This file is generated by The Interactive Disassembler (IDA)	    บ
; บ	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    บ
; บ			 Licensed to: Freeware version			    บ
; ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
;
; Input	MD5   :	9C0D1B1E26463EE2A0EB7BE85790C281

; File Name   :	C:\Users\Cyber_User\Documents\Magshimim\Computer-Architecture\Week 5\HW_ItayN\CODE03.com
; Format      :	MS-DOS COM-file
; Base Address:	0h Range: 100h-1ABh Loaded length: ABh


.model tiny


; Segment type:	Pure code
seg000 segment byte public 'CODE' use16
assume cs:seg000
org 100h
assume es:nothing, ss:nothing, ds:seg000, fs:nothing, gs:nothing




start proc near
mov	si, 1A2h

loc_103:
mov	al, [si]
cmp	al, 0
jz	short loc_110
xor	al, 1
mov	[si], al
inc	si
jmp	short loc_103

loc_110:
mov	ah, 9
mov	dx, 18Dh
int	21h		; DOS -	PRINT STRING
			; DS:DX	-> string terminated by	"$"
mov	di, 0
mov	si, 1A2h

loc_11D:
mov	ah, 0
int	16h		; KEYBOARD - READ CHAR FROM BUFFER, WAIT IF EMPTY
			; Return: AH = scan code, AL = character
cmp	al, 0Dh
jz	short loc_13C
mov	dl, al
mov	ah, 2
int	21h		; DOS -	DISPLAY	OUTPUT
			; DL = character to send to standard output
cmp	dl, [si]
jz	short loc_132
mov	di, 1

loc_132:
inc	si
cmp	byte ptr [si], 0
jnz	short loc_11D
or	di, di
jz	short loc_142

loc_13C:
mov	dx, 14Bh
jmp	short loc_145
db  90h	; 

loc_142:
mov	dx, 162h

loc_145:
mov	ah, 9
int	21h		; DOS -	PRINT STRING
			; DS:DX	-> string terminated by	"$"
int	20h		; DOS -	PROGRAM	TERMINATION
start endp		; returns to DOS--identical to INT 21/AH=00h

db  0Dh
db  0Ah
db  4Dh	; M
db  61h	; a
db  6Eh	; n
db  2Ch	; ,
db  20h
db  79h	; y
db  6Fh	; o
db  75h	; u
db  27h	; '
db  72h	; r
db  65h	; e
db  20h
db  77h	; w
db  72h	; r
db  6Fh	; o
db  6Eh	; n
db  67h	; g
db  21h	; !
db  0Dh
db  0Ah
db  24h	; $
db  0Dh
db  0Ah
db  59h	; Y
db  6Fh	; o
db  75h	; u
db  20h
db  61h	; a
db  72h	; r
db  65h	; e
db  20h
db  77h	; w
db  6Fh	; o
db  6Eh	; n
db  64h	; d
db  65h	; e
db  72h	; r
db  66h	; f
db  75h	; u
db  6Ch	; l
db  2Ch	; ,
db  20h
db  74h	; t
db  68h	; h
db  61h	; a
db  74h	; t
db  27h	; '
db  73h	; s
db  20h
db  74h	; t
db  68h	; h
db  65h	; e
db  20h
db  70h	; p
db  61h	; a
db  73h	; s
db  73h	; s
db  77h	; w
db  6Fh	; o
db  72h	; r
db  64h	; d
db  0Dh
db  0Ah
db  24h	; $
db  45h	; E
db  6Eh	; n
db  74h	; t
db  65h	; e
db  72h	; r
db  20h
db  74h	; t
db  68h	; h
db  65h	; e
db  20h
db  70h	; p
db  61h	; a
db  73h	; s
db  73h	; s
db  77h	; w
db  6Fh	; o
db  72h	; r
db  64h	; d
db  3Ah	; :
db  20h
db  24h	; $
db  42h	; B
db  42h	; B
db  43h	; C
db  43h	; C
db  44h	; D
db  44h	; D
db  45h	; E
db  45h	; E
db    0
seg000 ends


end start
