

;
; ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ	This file is generated by The Interactive Disassembler (IDA)	    บ
; บ	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    บ
; บ			 Licensed to: Freeware version			    บ
; ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
;
; Input	MD5   :	376830CBBCC3F16C5E826D6D67FDD037

; File Name   :	C:\Users\Cyber_User\Documents\Magshimim\Computer-Architecture\Week 5\HW_ItayN\CODE04.com
; Format      :	MS-DOS COM-file
; Base Address:	0h Range: 100h-1BBh Loaded length: BBh


.model tiny


; Segment type:	Pure code
seg000 segment byte public 'CODE' use16
assume cs:seg000
org 100h
assume es:nothing, ss:nothing, ds:seg000, fs:nothing, gs:nothing




start proc near
mov	cx, 0
mov	ah, 9
mov	dx, 190h
int	21h		; DOS -	PRINT STRING
			; DS:DX	-> string terminated by	"$"

loc_10A:
mov	ah, 0
int	16h		; KEYBOARD - READ CHAR FROM BUFFER, WAIT IF EMPTY
			; Return: AH = scan code, AL = character
mov	dl, al
mov	ah, 2
int	21h		; DOS -	DISPLAY	OUTPUT
			; DL = character to send to standard output
cmp	dl, 0Dh
jz	short loc_11D
add	cl, dl
jmp	short loc_10A

loc_11D:
mov	ah, 9
mov	dx, 1A2h
int	21h		; DOS -	PRINT STRING
			; DS:DX	-> string terminated by	"$"
mov	si, 0

loc_127:
mov	ah, 0
int	16h		; KEYBOARD - READ CHAR FROM BUFFER, WAIT IF EMPTY
			; Return: AH = scan code, AL = character
mov	dl, al
mov	ah, 2
int	21h		; DOS -	DISPLAY	OUTPUT
			; DL = character to send to standard output
cmp	dl, 0Dh
jz	short loc_13B
inc	si
sub	cl, dl
jmp	short loc_127

loc_13B:
cmp	si, 4
jb	short loc_14B
cmp	cl, 1
jnz	short loc_14B
mov	dx, 173h
jmp	short loc_14E
db  90h	; 

loc_14B:
mov	dx, 154h

loc_14E:
mov	ah, 9
int	21h		; DOS -	PRINT STRING
			; DS:DX	-> string terminated by	"$"
int	20h		; DOS -	PROGRAM	TERMINATION
start endp		; returns to DOS--identical to INT 21/AH=00h

db  0Dh
db  0Ah
db  4Eh	; N
db  6Fh	; o
db  20h
db  77h	; w
db  61h	; a
db  79h	; y
db  2Eh	; .
db  2Eh	; .
db  20h
db  54h	; T
db  68h	; h
db  61h	; a
db  74h	; t
db  27h	; '
db  73h	; s
db  20h
db  6Eh	; n
db  6Fh	; o
db  74h	; t
db  20h
db  72h	; r
db  69h	; i
db  67h	; g
db  68h	; h
db  74h	; t
db  21h	; !
db  0Dh
db  0Ah
db  24h	; $
db  0Dh
db  0Ah
db  57h	; W
db  6Fh	; o
db  77h	; w
db  20h
db  79h	; y
db  6Fh	; o
db  75h	; u
db  20h
db  61h	; a
db  72h	; r
db  65h	; e
db  20h
db  74h	; t
db  68h	; h
db  65h	; e
db  20h
db  6Dh	; m
db  61h	; a
db  6Eh	; n
db  20h
db    1
db    2
db    1
db    2
db  0Dh
db  0Ah
db  24h	; $
db  45h	; E
db  6Eh	; n
db  74h	; t
db  65h	; e
db  72h	; r
db  20h
db  79h	; y
db  6Fh	; o
db  75h	; u
db  72h	; r
db  20h
db  6Eh	; n
db  61h	; a
db  6Dh	; m
db  65h	; e
db  3Ah	; :
db  20h
db  24h	; $
db  0Dh
db  0Ah
db  45h	; E
db  6Eh	; n
db  74h	; t
db  65h	; e
db  72h	; r
db  20h
db  79h	; y
db  6Fh	; o
db  75h	; u
db  72h	; r
db  20h
db  70h	; p
db  61h	; a
db  73h	; s
db  73h	; s
db  77h	; w
db  6Fh	; o
db  72h	; r
db  64h	; d
db  3Ah	; :
db  20h
db  24h	; $
db    0
seg000 ends


end start
