

;
; ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ	This file is generated by The Interactive Disassembler (IDA)	    บ
; บ	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    บ
; บ			 Licensed to: Freeware version			    บ
; ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
;
; Input	MD5   :	C25617AA2C2A9A6004D5584DA5FDA3D9

; File Name   :	C:\Users\Cyber_User\Documents\Magshimim\Computer-Architecture\Week 5\HW_ItayN\CODE01.com
; Format      :	MS-DOS COM-file
; Base Address:	1000h Range: 10100h-1018Ch Loaded length: 8Ch



		.model tiny

; อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

; Segment type:	Pure code
seg000		segment	byte public 'CODE' use16
		assume cs:seg000
		org 100h
		assume es:nothing, ss:nothing, ds:seg000, fs:nothing, gs:nothing

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B	R O U T	I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ



start		proc near
		mov	dx, 145h
		mov	ah, 9
		int	21h		; DOS -	PRINT STRING
					; DS:DX	-> string terminated by	"$"
		mov	dx, 180h
		mov	ah, 0Ah
		int	21h		; DOS -	BUFFERED KEYBOARD INPUT
					; DS:DX	-> buffer
		push	dx
		push	ax
		mov	dx, 17Dh
		mov	ah, 9
		int	21h		; DOS -	PRINT STRING
					; DS:DX	-> string terminated by	"$"
		pop	ax
		pop	dx
		xor	cx, cx
		mov	cl, 9
		xor	bx, bx

loc_1011F:				; CODE XREF: start+2Cj
		mov	al, [bx+182h]
		mov	ah, [bx+133h]
		cmp	al, ah
		jnz	short loc_1013D
		inc	bx
		loop	loc_1011F
		mov	dx, 16Ch
		jmp	short loc_10140
; ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
		db  64h	; d
		db  63h	; c
		db  76h	; v
		db  68h	; h
		db  6Fh	; o
		db  6Ah	; j
		db  75h	; u
		db  72h	; r
		db  63h	; c
		db    0
; ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ

loc_1013D:				; CODE XREF: start+29j
		mov	dx, 15Ah

loc_10140:				; CODE XREF: start+31j
		mov	ah, 9
		int	21h		; DOS -	PRINT STRING
					; DS:DX	-> string terminated by	"$"
		retn
start		endp

; ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
		db  45h	; E
		db  6Eh	; n
		db  74h	; t
		db  65h	; e
		db  72h	; r
		db  20h
		db  74h	; t
		db  68h	; h
		db  65h	; e
		db  20h
		db  70h	; p
		db  61h	; a
		db  73h	; s
		db  73h	; s
		db  77h	; w
		db  6Fh	; o
		db  72h	; r
		db  64h	; d
		db  3Ah	; :
		db  20h
		db  24h	; $
		db  57h	; W
		db  72h	; r
		db  6Fh	; o
		db  6Eh	; n
		db  67h	; g
		db  20h
		db  70h	; p
		db  61h	; a
		db  73h	; s
		db  73h	; s
		db  77h	; w
		db  6Fh	; o
		db  72h	; r
		db  64h	; d
		db  21h	; !
		db  0Ah
		db  0Dh
		db  24h	; $
		db  52h	; R
		db  69h	; i
		db  67h	; g
		db  68h	; h
		db  74h	; t
		db  20h
		db  70h	; p
		db  61h	; a
		db  73h	; s
		db  73h	; s
		db  77h	; w
		db  6Fh	; o
		db  72h	; r
		db  64h	; d
		db  21h	; !
		db  20h
		db    1
		db  0Ah
		db  0Dh
		db  24h	; $
		db  0Ah
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
seg000		ends


		end start
