

;
; ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
; บ	This file is generated by The Interactive Disassembler (IDA)	    บ
; บ	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    บ
; บ			 Licensed to: Freeware version			    บ
; ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
;
; Input	MD5   :	E801B191948014ABCA0DD41CF6114934

; File Name   :	C:\Users\Cyber_User\Documents\Magshimim\Computer-Architecture\Week7-Safes\Class-Safes\ADDING.com
; Format      :	MS-DOS COM-file
; Base Address:	0h Range: 100h-108h Loaded length: 8h


		.model tiny

; อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

; Segment type:	Pure code
seg000		segment	byte public 'CODE' use16
		assume cs:seg000
		org 100h
		assume es:nothing, ss:nothing, ds:seg000, fs:nothing, gs:nothing

; ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ S U B	R O U T	I N E ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ



start		proc near		; CODE XREF: start+6j
		add	ds:0DEDh, ax
		xor	cx, cx
		loop	start
start		endp

seg000		ends


		end start
